log_level = "DEBUG"

[options]
work_filter = '.*(香港|Hong Kong|HK|Japan|美国|United States|US).*(?<!\.)(1|2|3|4)|work|home-trojan-v6|ekko.*|dler.*'

[[uploader]]
name = 'gist'
type = 'gist'
# https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
token = "ENV_GH_TOKEN"
id = "a188d6b32ddf7cf3bbc9554055e5e2a4"

[[provider]]
name = "主力机场"
type = "clash-meta"
file = "meta.yaml"

[[provider]]
name = "Surge 测试本地"
type = "surge"
file = 'surge.conf'

[[provider]]
name = "Surge 测试"
type = "surge"
url = "https://gist.github.com/EkkoG/623bfd3be62a68b831c29007305ebbc2/raw/surge.conf"
[provider.rename]
add_prefix = "备用机场-"
replace = [
  {old = "节点", new = "机场"}
]

[[provider]]
name = "自建节点"
type = "custom"
file = 'self.toml'


[[artifact]]
name = "ekko-meta.yaml"
type = "clash-meta"
template = "clash.yaml"
providers = ["自建节点", "主力机场", "Surge 测试"]
[artifact.options]
work = true

[[artifact]]
name = "ekko2.yaml"
type = "clash"
template = "clash.yaml"
providers = ["自建节点", "主力机场"]
[artifact.options]
work = true

[[artifact]]
name = "ekko-stash.yaml"
type = "stash"
template = "clash.yaml"
providers = ["自建节点", "主力机场"]
[artifact.options]
work = true

[[artifact]]
name = "ekko-surge.conf"
type = "surge"
template = "surge.conf"
providers = ["自建节点", "主力机场", "Surge 测试", 'Surge 测试本地']
[artifact.options]
work = true
[[artifact.upload]]
to = "gist"
[[artifact.upload]]
to = "gist"
file_name = 'clash-for-xx.yml'

[[artifact]]
name = "dae.conf"
type = "dae"
template = "dae.conf"
providers = ["自建节点", "主力机场", "Surge 测试", 'Surge 测试本地']
[artifact.options]
work = true

[[ruleset]]
name = "telegram"
url = "https://github.com/DivineEngine/Profiles/raw/master/Surge/Ruleset/Extra/Telegram/Telegram.list"