log-level = "DEBUG"

[[provider]]
name = "主力机场"
type = "clash-meta"
file = "meta.yaml"

[[provider]]
name = "Surge 测试本地"
type = "surge"
file = 'surge.conf'

[[provider]]
name = "Surge 测试"
type = "surge"
url = "https://gist.github.com/EkkoG/623bfd3be62a68b831c29007305ebbc2/raw/surge.conf"
[provider.rename]
add-prefix = "备用机场-"
replace = [
  {old = "节点", new = "机场"}
]

[[provider]]
name = "自建节点"
type = "custom"
file = 'self.toml'


[[artifact]]
name = "ekko-meta.yaml"
type = "clash-meta"
template = "clash.yaml"
providers = ["自建节点", "主力机场", "Surge 测试"]
[artifact.options]
work = true

[[artifact]]
name = "ekko2.yaml"
type = "clash"
template = "clash.yaml"
providers = ["自建节点", "主力机场"]
[artifact.options]
work = true

[[artifact]]
name = "ekko-stash.yaml"
type = "stash"
template = "clash.yaml"
providers = ["自建节点", "主力机场"]
[artifact.options]
work = true

[[artifact]]
name = "ekko-surge.conf"
type = "surge"
template = "surge.conf"
providers = ["自建节点", "主力机场", "Surge 测试", 'Surge 测试本地']
[artifact.options]
work = true

[[artifact]]
name = "dae.conf"
type = "dae"
template = "dae.conf"
providers = ["自建节点", "主力机场", "Surge 测试", 'Surge 测试本地']
[artifact.options]
work = true

[[ruleset]]
name = "telegram"
url = "https://github.com/DivineEngine/Profiles/raw/master/Surge/Ruleset/Extra/Telegram/Telegram.list"