log-level = "DEBUG"

[[provider]]
name = "主力机场"
type = "clash-meta"
file = "meta.yaml"

[[provider]]
name = "Surge 测试"
type = "surge"
url = "https://gist.github.com/EkkoG/623bfd3be62a68b831c29007305ebbc2/raw/surge.conf"

[[provider]]
name = "自建节点"
type = "custom"
[[provider.nodes]]
type = 'http'
name = 'ekko-https-ahhh'
server = 'example.com'
port = 4443
tls = true
username = 'ekko'
password = 'ahh'

[[artifact]]
name = "ekko-meta.yaml"
type = "clash-meta"
template = "clash.yaml"
providers = ["自建节点", "主力机场", "Surge 测试"]
[artifact.options]
work = true

[[artifact]]
name = "ekko2.yaml"
type = "clash"
template = "clash.yaml"
providers = ["自建节点", "主力机场"]
[artifact.options]
work = true

[[artifact]]
name = "ekko-stash.yaml"
type = "stash"
template = "clash.yaml"
providers = ["自建节点", "主力机场"]
[artifact.options]
work = true

[[artifact]]
name = "ekko-surge.conf"
type = "surge"
template = "surge.conf"
providers = ["自建节点", "主力机场", "Surge 测试"]
[artifact.options]
work = true

[[ruleset]]
name = "telegram"
url = "https://github.com/DivineEngine/Profiles/raw/master/Surge/Ruleset/Extra/Telegram/Telegram.list"